name: "Deploy to GitHub Pages"

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Info
      run: |
        echo ${GITHUB_ACTOR}

    - name: Checkout repository
      uses: actions/checkout@v2
#       with:
#         persist-credentials: true
#         token: ${ secrets.GITHUB_TOKEN }

    - name: Install requirements
      run: npm install

    - name: Deploy
      run: |
        git config user.name ${GITHUB_ACTOR}
        git config user.email ${GITHUB_ACTOR}@gmail.com
        npm run deploy
