name: "Deploy to GitHub Pages"

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
#     permissions:
#       contents: write

    steps:
    - name: Info
      run: |
        echo $GITHUB_ACTORgmail
        echo ${{ github.actor }}gmail
    - name: Checkout repository
      uses: actions/checkout@v2
#       with:
#         persist-credentials: true
#         token: ${ secrets.GITHUB_TOKEN }

    - name: Install requirements
      run: npm install

    - name: Deploy
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email $GITHUB_ACTOR@gmail.com
        git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        npm run deploy
